name: S3 deploy
run-name: ${{ github.actor }} is deploying
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout [secret-spot-website] current branch
        uses: actions/checkout@v4
        with:
          path: src

      #####
      # Build artifacts
      #####
      - name: Build artifacts
        run: |
          docker run -v ./src:/src --rm hugomods/hugo hugo

      #####
      # Artifacts deploying
      #####
      - name: Deploy artifacts to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: 'by-secret-spot-website'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_TILES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_TILES_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'src/public'
