name: Deploy
run-name: ${{ github.actor }} is deploying
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout [secret-spot-website] current branch
        uses: actions/checkout@v4
        with:
          path: src
          submodules: true

      #####
      # Build artifacts
      #####
      - name: Build artifacts
        run: |
          docker run -v ./src:/src --rm hugomods/hugo hugo

      - name: Deploy artifacts to S3 bucket
        run: |
          aws s3 sync --delete ./src/public/ s3://by-secret-spot-website/

      #####
      # Invalidate CF
      #####
      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CF_DISTRIBUTION_ID }} \
            --paths "/*"
